--- # Build and deploy packages
name: 'Upload sarif files'
description: 'Builds and deploys the source'
inputs:
  # GENERAL
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  REPO_VISIBILITY:
    description: 'Visibility of the repo'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Sarif Files to upload"
      shell: bash
      working-directory: ${{github.workspace}}/results
      run: |
        ls -la
        echo "Hash: ${{ hashfiles('**/*.sarif') }}"
        echo "SARIF_HASH=${{ hashfiles('**/*.sarif') }}" >> $GITHUB_ENV

    - if: ${{github.event_name == 'pull_request' && env.SARIF_HASH != ''}}
      name: Post SARIF findings in the pull request
      uses: sett-and-hive/sarif-to-comment-action@v1
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        branch: ${{ github.head_ref }}
        pr-number: ${{ github.event.number }}
        sarif-file: results/*.sarif
        title: Analysis issues
        dry-run: false

    - if: ${{inputs.REPO_VISIBILITY == 'public' && env.SARIF_HASH != ''}}
      name: "Upload SARIF file for diagnostics"
      id: sarif
      uses: github/codeql-action/upload-sarif@v2.12.7
      with:
        sarif_file: ${{github.workspace}}/results
        category: dotnet
        token: ${{github.token}}
        wait-for-processing: true

    - name: "Sarif Upload Summary"
      shell: bash
      working-directory: ${{github.workspace}}/results
      run: |
         echo "Sarif Upload Completed"
         echo "sarifId: ${{steps.sarif.outputs.sarif-id}}"
