--- # Build and deploy packages
name: 'Upload sarif files'
description: 'Builds and deploys the source'
inputs:
  # GENERAL
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  REPO_VISIBILITY:
    description: 'Visibility of the repo'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Sarif Files to upload"
      shell: bash
      working-directory: ${{github.workspace}}/results
      run: |
        ls -la
        rm -rf *.Tests.sarif
        echo "Hash: ${{ hashfiles('**/*.sarif') }}"
        echo "SARIF_HASH=${{ hashfiles('**/*.sarif') }}" >> $GITHUB_ENV
        cat *.sarif

    - if: ${{inputs.REPO_VISIBILITY == 'public' && env.SARIF_HASH != ''}}
      name: Violation Comments Action
      uses: tomasbjerre/violation-comments-action@1.0.5
      with:
        parser: SARIF
         regexp: 'results/.*\.sarif$'
        keepOldComments: true # remove the old comments, or keep them
        commentTemplate: '{{violation.message}}'
        maxNumberOfViolations: 999 # Will only post this many comments
        severity: INFO # INFO, WARN or ERROR
        commentOnlyChangedContent: true # Comment only if violations in the changed part of PR
        commentOnlyChangedFiles: true # Comment only on the files that are changed in PR
        createSingleFileComments: true # Comment several comments, for each violation
        createCommentWithAllSingleFileComments: false # Create on big comment with all violations

    - if: ${{inputs.REPO_VISIBILITY == 'public' && env.SARIF_HASH != ''}}
      name: "Upload SARIF file for diagnostics"
      id: sarif
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{github.workspace}}/results
        category: dotnet
        token: ${{github.token}}
        wait-for-processing: true

    - name: "Sarif Upload Summary"
      shell: bash
      working-directory: ${{github.workspace}}/results
      run: |
         echo "Sarif Upload Completed"
         echo "sarifId: ${{steps.sarif.outputs.sarif-id}}"
